### ISSUE TITLE
support on 6.3.0

### ISSUE THREAD

**Issue by SamikshaJain** [chrisfischer/kibana-button-vis#1]
Is it supported on 6.3.0 kibana?

**Comment by chrisfischer** [comment]
Yes, you can see in package.json that that is the listed Kibana version number. It may work with other versions as well, but I haven’t tried it.

**Comment by SamikshaJain** [comment]
Thanks for quick reply. Any way i can install this using kibana-plugin install command ?
Can you send zip file location

**Comment by chrisfischer** [comment]
https://github.com/chrisfischer/kibana-button-vis/releases/download/v6.3.0/button_vis-0.0.0.zip
